name: GCP Compute Engine Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to GCP Compute Engine 
        env:
          SERVER_HOST: ${{ secrets.server_conf.SERVER_HOST }}
          SERVER_KEY: ${{ secrets.server_conf.SERVER_KEY }}
          SERVER_USER: ${{ secrets.server_conf.SERVER_USER }} 
        run: |
            echo "Server Host: $SERVER_HOST"
            echo "Server Key: $SERVER_KEY"
            echo "Server User: $SERVER_USER"