name: Python Application Deployment

on:
  push:
    branches:
      - main  # Set this to the branches you want to trigger the deployment.

jobs:
  deployment:
    runs-on: ubuntu-latest # The type of runner that the job will run on

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # This action checks out your repository under $GITHUB_WORKSPACE so that your workflow can access its contents.

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Setup Python version required for your project

    - name: Install dependencies (if required)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have a requirements.txt

    - name: Test  # Optional: run tests here if you have any
      run: |
        python -m unittest discover

    - name: SSH and Deploy Python code to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          # Commands to run on your server
          cd /path/to/your/application/directory  # Adjust path as necessary
          git pull
          # Optionally any build or restart commands
          python main.py  # Execute your main Python file or replace with proper command
