name: Deploy to GCP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: server_conf
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Deploy to GCP Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_KEY: ${{ secrets.SERVER_KEY }}
          DEPLOY_DIR: /home/bilal.ah/project
        run: |
          # Save the SSH key
          echo "$SERVER_KEY" > server_key.pem
          chmod 600 server_key.pem

          # Install rsync on the server
          ssh -i server_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST 'sudo apt-get update && sudo apt-get install -y rsync'

          # Sync files to the server
          rsync -avz -e "ssh -i server_key.pem -o StrictHostKeyChecking=no" ./ $SERVER_USER@$SERVER_HOST:$DEPLOY_DIR/

          # Execute commands on the server
          ssh -i server_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
            cd project
            ls
            # Kill the existing application process
            pkill -f "python3 main.py"
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            nohup python3 main.py > output.log 2>&1 &
          EOF

          # Clean up
          rm server_key.pem
