name: Python Application CI/CD

# This specifies when the workflow should run. 
# 'push' triggers the workflow on every push to the specified branches.
on:
  push:
    branches: [main]  # You can specify any branch which suits your workflow needs.

jobs:  # Jobs are tasks that run in parallel unless otherwise specified.
  deploy:  # This is an identifier for the job.
    runs-on: ubuntu-latest  # Specifies the type of runner that the job will run on.

    steps:  # Steps are tasks that execute sequentially within a job.
    - name: Checkout Repository
      uses: actions/checkout@v2  # This action checks out your repository under $GITHUB_WORKSPACE, so your job can access the contents of your repository.

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specifies the Python version to set up.

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assumes you have a 'requirements.txt' file.

    - name: Run Tests  # Optional step to run tests.
      run: |
        python -m unittest discover  # Example of how to run Python unittests.

    - name: SSH and Deploy to GCP VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVERUSERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          cd /path/to/your/application
          git pull
          python main.py  # Runs your main Python script, adjust as necessary.
