name: GCP Compute Engine Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: server_conf
    env:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_KEY: ${{ secrets.SERVER_KEY }}
      SERVER_USER: ${{ secrets.SERVER_USER }} 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create SSH Key File
        id: create-key
        run: |
          mkdir -p ~/.ssh
          echo "$SERVER_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Disable SSH Strict Host Key Checking
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy to GCP Compute Engine
      
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_HOST "git pull origin main && python main.py"
